services:
  chatapp:
    image: chatapp
    build:
      context: .
      dockerfile: ChatApp/Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__Default=Host=db;Port=5432;Database=ChatAppDB;Username=admin;Password=admin

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ChatAppDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: